name: affinity_destiny
description: "for management of private relationship"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_langdetect: ^0.0.2
  get: ^4.6.6
  ionicons: ^0.2.2
  pinyin: ^3.3.0
  wrapper: ^1.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/avatar/
